language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'  
install:
  - yarn --pure-lockfile
before_script:  
  - git checkout master
  - lerna updated --json
script:  
  - yarn build
  - yarn test    
after_success:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - git config --global user.email "dave.garwacke@ifyoumakeit.com"
  - git config --global user.name "Travis CI"  
  - .travis/after_success.sh  
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
