language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    tags: true
install:
  - yarn
before_script:   
  - lerna updated --json
script:  
  - yarn build
  - yarn test    
after_success:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.token $GITHUB_TOKEN
  - git diff
  - .travis/after_success.sh  
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
