language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'  
before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - yarn lerna bootstrap
after_success: .travis/after_success.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
