language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'  
before_script:
  - chmod +x ./travis/after_success.sh
after_success: ./travis/after_success.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
